/* ─────────────────────────────────────────────────────────────
   MeinMagenta Prototype — Content Data
   Edit this file to update all screen content without touching UI code.
   ───────────────────────────────────────────────────────────── */

/* ─── User ─────────────────────────────────────────────────── */
export const USER = {
  firstName: 'Jana',
  lastName:  'Meyer',
  initials:  'JM',
};

/* ─── Contracts (shown as tabs + cards on Overview) ────────── */
export const CONTRACTS = [
  {
    id:      'mobile-1',
    type:    'mobile',
    label:   'Magenta XL',
    number:  '+49 111 111 1111',
    data:    { usedGB: 15.8, totalGB: 20 },
  },
  {
    id:      'mobile-2',
    type:    'mobile',
    label:   'Magenta L',
    number:  '+49 222 222 2222',
    data:    null,
  },
  {
    id:      'home-1',
    type:    'home',
    label:   'Magenta Zuhause Internet',
    number:  null,
    data:    null,
  },
  {
    id:      'tv-1',
    type:    'tv',
    label:   'MagentaTV',
    number:  null,
    data:    null,
  },
];

/* ─── Banners (urgency / promo cards on Overview) ──────────── */
export const BANNERS = [
  {
    id:          'bills-ready',
    variant:     'urgent',       // 'urgent' (dark) | 'promo' (light)
    title:       'Ihre Rechnung ist da',
    subtitle:    '2 offene Rechnungen · Fällig am 15. Juni',
    cta:         'Rechnung ansehen',
    ctaAction:   'openInvoice',
    dismissible: false,
  },
  {
    id:          'roaming-promo',
    variant:     'promo',
    title:       'Im Ausland? Wählen Sie Ihr passendes Roaming-Paket. ✈️',
    subtitle:    null,
    cta:         'Roaming-Pakete ansehen',
    ctaAction:   'openRoaming',
    dismissible: true,
  },
];

/* ─── Notifications ─────────────────────────────────────────── */
export const NOTIFS = [
  {
    id:          '1',
    type:        'invoice',
    headline:    'Ihre Rechnung ist diesen Monat um 4,20 € gestiegen',
    summary:     'Ihr 6-Monats-Rabatt ist am 1. Juni ausgelaufen. Das war zu erwarten.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'heute, 13:16',
    isNew:       true,
    status:      'noActionNeeded',
    cta:         'Was hat sich geändert?',
    ctaVariant:  'primary',
    hasDocument: true,
  },
  {
    id:          '2',
    type:        'invoice',
    headline:    'Ihre Rechnung ist da — 39,99 € fällig bis 15. Jun',
    summary:     'Bitte zahlen Sie bis zum 15. Juni — dann bleibt alles im grünen Bereich.',
    service:     'Magenta XL',
    contractId:  'mobile-1',
    date:        'heute, 08:00',
    isNew:       true,
    status:      'actionRequired',
    cta:         'Jetzt bezahlen',
    ctaVariant:  'primary',
    hasDocument: true,
  },
  {
    id:          '3',
    type:        'data',
    headline:    'Sie haben noch 4,2 GB diesen Monat',
    summary:     'Bei Ihrem aktuellen Verbrauch reicht das noch etwa 3 Tage.',
    service:     'Magenta XL',
    contractId:  'mobile-1',
    date:        'heute, 10:31',
    isNew:       true,
    status:      'actionRequired',
    cta:         'Datenvolumen hinzubuchen',
    ctaVariant:  'primary',
    hasDocument: false,
  },
  {
    id:          '4',
    type:        'order',
    headline:    'Ihr Router ist unterwegs',
    summary:     'Lieferung morgen zwischen 10:00 und 14:00 Uhr.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'gestern, 17:42',
    isNew:       true,
    status:      'inProgress',
    cta:         'Sendung verfolgen',
    ctaVariant:  'primary',
    hasDocument: false,
  },
  {
    id:          '5',
    type:        'contract',
    headline:    'Wir haben Ihren Magenta XL Vertrag aktualisiert',
    summary:     'Ihr monatlicher Preis bleibt gleich. Sie müssen nichts tun.',
    service:     'Magenta XL',
    contractId:  'mobile-1',
    date:        'gestern, 09:00',
    isNew:       false,
    status:      'noActionNeeded',
    cta:         'Vertrag ansehen',
    ctaVariant:  'secondary',
    hasDocument: true,
  },
  {
    id:          '6',
    type:        'order',
    headline:    'Ihr Glasfaser-Termin ist für den 18. Jun bestätigt',
    summary:     'Der Techniker kommt zwischen 09:00 und 13:00 Uhr. Bitte sorgen Sie dafür, dass jemand zu Hause ist.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'vor 3 Tagen',
    isNew:       false,
    status:      'actionRequired',
    cta:         'Termin ansehen',
    ctaVariant:  'primary',
    hasDocument: false,
  },
  {
    id:          '7',
    type:        'invoice',
    headline:    'Wir haben Ihre Zahlung erhalten — 39,99 €',
    summary:     'Danke. Alles ist beglichen.',
    service:     'Magenta XL',
    contractId:  'mobile-1',
    date:        'vor 4 Tagen',
    isNew:       false,
    status:      'noActionNeeded',
    cta:         null,
    ctaVariant:  'none',
    hasDocument: false,
  },
  {
    id:          '8',
    type:        'contract',
    headline:    'Sie nutzen jetzt Magenta XL — aktiv seit heute',
    summary:     'Ihr monatlicher Preis beträgt 39,99 €. Ihr Datenvolumen ist jetzt 20 GB.',
    service:     'Magenta XL',
    contractId:  'mobile-1',
    date:        'vor 5 Tagen',
    isNew:       false,
    status:      'noActionNeeded',
    cta:         'Neuen Vertrag ansehen',
    ctaVariant:  'secondary',
    hasDocument: true,
  },
  {
    id:          '9',
    type:        'document',
    headline:    'Ihr Vertragsdokument steht bereit',
    summary:     'Unterzeichnet am 31. Mai 2026.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'vor 1 Woche',
    isNew:       false,
    status:      'noActionNeeded',
    cta:         'Dokument herunterladen',
    ctaVariant:  'secondary',
    hasDocument: true,
  },
  {
    id:          '10',
    type:        'data',
    headline:    'Datenvolumen aufgebraucht — Ihre Verbindung ist jetzt langsamer',
    summary:     'Buchen Sie ein Datenpaket, um sofort wieder volle Geschwindigkeit zu haben.',
    service:     'Magenta L',
    contractId:  'mobile-2',
    date:        'vor 1 Woche',
    isNew:       false,
    status:      'actionRequired',
    cta:         'Datenpaket hinzubuchen',
    ctaVariant:  'primary',
    hasDocument: false,
  },
  {
    id:          '11',
    type:        'order',
    headline:    'Ihr Miet-Router muss bis zum 20. Jun zurück',
    summary:     'Das Rücksendeetikett liegt in der Box. Bei pünktlicher Rückgabe entstehen keine Kosten.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'vor 1 Woche',
    isNew:       false,
    status:      'actionRequired',
    cta:         'Rückgabe-Details ansehen',
    ctaVariant:  'primary',
    hasDocument: false,
  },
  {
    id:          '12',
    type:        'info',
    headline:    'Wir haben Ihren Umzugsauftrag erhalten',
    summary:     'Wir prüfen die Verfügbarkeit an Ihrer neuen Adresse und melden uns.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'vor 2 Wochen',
    isNew:       false,
    status:      'inProgress',
    cta:         'Auftragsstatus ansehen',
    ctaVariant:  'secondary',
    hasDocument: false,
  },
  {
    id:          '13',
    type:        'contract',
    headline:    'Wir haben Ihre Kündigung von Magenta L bestätigt',
    summary:     'Ihr Vertrag endet am 31. Jul 2026. Ihre Nummer bleibt bis dahin aktiv.',
    service:     'Magenta L',
    contractId:  'mobile-2',
    date:        'vor 2 Wochen',
    isNew:       false,
    status:      'noActionNeeded',
    cta:         'Bestätigung ansehen',
    ctaVariant:  'secondary',
    hasDocument: true,
  },
  {
    id:          '14',
    type:        'invoice',
    headline:    'Ihre Rechnung ist diesen Monat um 5 € gesunken',
    summary:     'Ihr Treuerabatt ist jetzt aktiv. Er gilt für die nächsten 12 Monate.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'vor 3 Wochen',
    isNew:       false,
    status:      'noActionNeeded',
    cta:         'Rechnung ansehen',
    ctaVariant:  'secondary',
    hasDocument: true,
  },
  {
    id:          '15',
    type:        'info',
    headline:    'Ihr Internet ist wieder da — wir haben die Störung behoben',
    summary:     'Alles läuft seit 14:35 Uhr wieder normal.',
    service:     'Magenta Zuhause Internet',
    contractId:  'home-1',
    date:        'vor 3 Wochen',
    isNew:       false,
    status:      'noActionNeeded',
    cta:         null,
    ctaVariant:  'none',
    hasDocument: false,
  },
];

/* ─── Notification Details ────────────────────────────────── */
export const NOTIF_DETAILS = [
  {
    id: '1',
    title: 'Rechnung Internet — Juni 2026',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Ihre Rechnung ist um 4,20 € gestiegen',
      body: 'Ihr 6-Monats-Rabatt ist am 1. Juni ausgelaufen. Das ist jetzt der reguläre Preis für Ihren Fibre 1000 Tarif.',
      confirmChip: 'Diese Erhöhung ist planmäßig – Sie müssen nichts tun.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was hat sich geändert?',
      content: [
        { label: 'Fibre 1000 Grundpreis',       previous: '35,81 €',  current: '39,99 €', delta: '+4,18 €' },
        { label: 'Aktionsrabatt (abgelaufen)', previous: '−4,18 €', current: '0,00 €',  delta: '+4,18 €' },
      ],
    },
    primaryCta: 'Rechnung als PDF',
    feedbackBlock: true,
    secondaryCta: 'Hilfe anfordern',
  },
  {
    id: '2',
    title: 'Rechnung Mobilfunk — Juni 2026',
    serviceChip: 'Magenta XL',
    aiExplanation: {
      headline: 'Ihre Rechnung über 39,99 € ist fällig',
      body: 'Die Abbuchung ist für den 15. Juni geplant. Wenn Ihre Bankdaten aktuell sind, passiert alles automatisch.',
      confirmChip: 'Kein Handlungsbedarf, wenn Ihr SEPA-Lastschriftmandat aktiv ist.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was ist in dieser Rechnung?',
      content: [
        { label: 'Magenta XL Grundpreis', previous: null, current: '39,99 €',              delta: null },
        { label: 'Abrechnungszeitraum',   previous: null, current: '01.06. – 30.06.2026', delta: null },
      ],
    },
    primaryCta: 'Rechnung als PDF',
    feedbackBlock: false,
    secondaryCta: 'Bankdaten prüfen',
  },
  {
    id: '3',
    title: 'Datenvolumen — Juni 2026',
    serviceChip: 'Magenta XL · +49 111 111 1111',
    aiExplanation: {
      headline: 'Sie haben noch 4,2 GB von 20 GB',
      body: 'Sie haben diesen Monat bereits 15,8 GB verbraucht. Bei Ihrem aktuellen Tempo reicht das Restvolumen noch etwa 3 Tage.',
      confirmChip: 'Nach dem Aufbrauchen wird Ihre Verbindung automatisch gedrosselt.',
      confirmVariant: 'warning',
    },
    accordion: {
      label: 'Wie war mein Verbrauch?',
      content: [
        { label: 'Verbraucht',       previous: null, current: '15,8 GB',        delta: null },
        { label: 'Noch verfügbar',   previous: null, current: '4,2 GB',          delta: null },
        { label: 'Volumen wird am',  previous: null, current: '1. Juli erneuert',delta: null },
      ],
    },
    primaryCta: 'Datenvolumen hinzubuchen',
    feedbackBlock: false,
    secondaryCta: null,
  },
  {
    id: '4',
    title: 'Ihre Bestellung — Router',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Ihr Router wird morgen geliefert',
      body: 'Der DHL-Fahrer kommt voraussichtlich zwischen 10:00 und 14:00 Uhr. Sie erhalten vorab eine SMS mit einem genaueren Zeitfenster.',
      confirmChip: 'Kein Handlungsbedarf — wir benachrichtigen Sie, bevor der Fahrer kommt.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Bestelldetails',
      content: [
        { label: 'Produkt',       previous: null, current: 'Speedport Smart 4', delta: null },
        { label: 'Bestellnummer', previous: null, current: '#TK-2026-88412',    delta: null },
        { label: 'Versandart',    previous: null, current: 'DHL Express',        delta: null },
      ],
    },
    primaryCta: 'Sendung verfolgen',
    feedbackBlock: false,
    secondaryCta: null,
  },
  {
    id: '5',
    title: 'Vertragsänderung — Magenta XL',
    serviceChip: 'Magenta XL · +49 111 111 1111',
    aiExplanation: {
      headline: 'Wir haben Ihren Vertrag aktualisiert',
      body: 'Die Änderung betrifft die allgemeinen Geschäftsbedingungen. Ihr Preis und Ihr Datenvolumen bleiben unverändert.',
      confirmChip: 'Ihr monatlicher Beitrag von 39,99 € bleibt gleich.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was wurde geändert?',
      content: [
        { label: 'Monatlicher Preis', previous: '39,99 €', current: '39,99 €',        delta: 'Keine Änderung' },
        { label: 'Datenvolumen',      previous: '20 GB',   current: '20 GB',           delta: 'Keine Änderung' },
        { label: 'Vertragslaufzeit',  previous: null,       current: 'bis 31.05.2027', delta: null },
      ],
    },
    primaryCta: 'Vertrag als PDF',
    feedbackBlock: false,
    secondaryCta: 'Hilfe anfordern',
  },
  {
    id: '6',
    title: 'Installationstermin — Glasfaser',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Ihr Techniker-Termin ist am 18. Juni bestätigt',
      body: 'Der Techniker kommt zwischen 09:00 und 13:00 Uhr. Die Installation dauert in der Regel 2–3 Stunden. Bitte sorgen Sie dafür, dass jemand zu Hause ist.',
      confirmChip: 'Bitte halten Sie Ihren Hausanschlussraum zugänglich.',
      confirmVariant: 'info',
    },
    accordion: {
      label: 'Was passiert bei der Installation?',
      content: [
        { label: 'Datum',          previous: null, current: '18. Juni 2026',      delta: null },
        { label: 'Zeitfenster',    previous: null, current: '09:00 – 13:00 Uhr',  delta: null },
        { label: 'Dauer',          previous: null, current: 'ca. 2–3 Stunden',     delta: null },
        { label: 'Auftragsnummer', previous: null, current: '#FTTH-2026-04471',    delta: null },
      ],
    },
    primaryCta: 'Termin in Kalender eintragen',
    feedbackBlock: false,
    secondaryCta: 'Termin verschieben',
  },
  {
    id: '7',
    title: 'Zahlungseingang — Juni 2026',
    serviceChip: 'Magenta XL · +49 111 111 1111',
    aiExplanation: {
      headline: 'Wir haben Ihre Zahlung erhalten',
      body: 'Ihr Konto ist ausgeglichen. Die nächste Rechnung erhalten Sie am 1. Juli.',
      confirmChip: 'Alles ist beglichen – kein Handlungsbedarf.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Zahlungsdetails',
      content: [
        { label: 'Betrag',         previous: null, current: '39,99 €',         delta: null },
        { label: 'Eingegangen am', previous: null, current: '4. Juni 2026',     delta: null },
        { label: 'Zahlungsart',    previous: null, current: 'SEPA-Lastschrift', delta: null },
      ],
    },
    primaryCta: 'Beleg als PDF',
    feedbackBlock: false,
    secondaryCta: null,
  },
  {
    id: '8',
    title: 'Tarifwechsel — Magenta XL',
    serviceChip: 'Magenta XL · +49 111 111 1111',
    aiExplanation: {
      headline: 'Sie nutzen jetzt Magenta XL',
      body: 'Der Wechsel ist heute aktiv. Ihr neues Datenvolumen von 20 GB steht ab sofort zur Verfügung.',
      confirmChip: 'Ihr neuer Monatsbeitrag beträgt 39,99 €.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was hat sich geändert?',
      content: [
        { label: 'Tarif',        previous: 'Magenta L', current: 'Magenta XL', delta: null },
        { label: 'Monatspreis',  previous: '29,99 €',   current: '39,99 €',    delta: '+10,00 €' },
        { label: 'Datenvolumen', previous: '10 GB',     current: '20 GB',      delta: '+10 GB' },
        { label: 'Aktiv seit',   previous: null,        current: 'heute',       delta: null },
      ],
    },
    primaryCta: 'Neuen Vertrag als PDF',
    feedbackBlock: false,
    secondaryCta: null,
  },
  {
    id: '9',
    title: 'Ihr Vertragsdokument',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Ihr Vertragsdokument steht bereit',
      body: 'Der Vertrag für Ihren MagentaZuhause Internet Anschluss wurde am 31. Mai 2026 unterzeichnet und ist jetzt zum Download verfügbar.',
      confirmChip: 'Keine Aktion nötig — das Dokument ist zu Ihrer Ablage.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was ist in diesem Dokument?',
      content: [
        { label: 'Produkt',         previous: null, current: 'MagentaZuhause Fibre 1000', delta: null },
        { label: 'Monatspreis',     previous: null, current: '39,99 €',                   delta: null },
        { label: 'Vertragsbeginn',  previous: null, current: '1. Juni 2026',               delta: null },
        { label: 'Mindestlaufzeit', previous: null, current: '24 Monate',                  delta: null },
      ],
    },
    primaryCta: 'Dokument herunterladen',
    feedbackBlock: false,
    secondaryCta: null,
  },
  {
    id: '10',
    title: 'Datenvolumen aufgebraucht — Magenta L',
    serviceChip: 'Magenta L · +49 222 222 2222',
    aiExplanation: {
      headline: 'Ihr Datenvolumen ist aufgebraucht',
      body: 'Ihre Verbindung läuft jetzt mit reduzierter Geschwindigkeit. Sie können jederzeit ein Datenpaket hinzubuchen, um wieder die volle Geschwindigkeit zu nutzen.',
      confirmChip: 'Ihr Volumen wird am 1. Juli automatisch erneuert.',
      confirmVariant: 'warning',
    },
    accordion: {
      label: 'Was bedeutet reduzierte Geschwindigkeit?',
      content: [
        { label: 'Verbraucht',                previous: null, current: '10 GB von 10 GB', delta: null },
        { label: 'Aktuelle Geschwindigkeit',   previous: null, current: 'Reduziert',       delta: null },
        { label: 'Volumen erneuert am',        previous: null, current: '1. Juli 2026',    delta: null },
      ],
    },
    primaryCta: 'Datenpaket hinzubuchen',
    feedbackBlock: false,
    secondaryCta: 'Hilfe anfordern',
  },
  {
    id: '11',
    title: 'Rückgabe Miet-Router',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Ihr Miet-Router muss bis zum 20. Juni zurück',
      body: 'Das Rücksendeetikett liegt bereits in der Box. Geben Sie das Gerät einfach bei einer DHL-Filiale ab — ohne Kosten.',
      confirmChip: 'Bei pünktlicher Rückgabe entstehen keine weiteren Kosten.',
      confirmVariant: 'info',
    },
    accordion: {
      label: 'So geben Sie das Gerät zurück',
      content: [
        { label: 'Rückgabe bis', previous: null, current: '20. Juni 2026',           delta: null },
        { label: 'Versandart',   previous: null, current: 'DHL — Etikett liegt bei', delta: null },
        { label: 'Abgabeort',    previous: null, current: 'Jede DHL-Filiale',         delta: null },
        { label: 'Kosten',       previous: null, current: 'Kostenlos',                delta: null },
      ],
    },
    primaryCta: 'DHL-Filiale finden',
    feedbackBlock: false,
    secondaryCta: 'Hilfe anfordern',
  },
  {
    id: '12',
    title: 'Umzugsauftrag — Status',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Wir haben Ihren Umzugsauftrag erhalten',
      body: 'Wir prüfen gerade, ob Glasfaser an Ihrer neuen Adresse verfügbar ist. Das dauert in der Regel 2–3 Werktage. Sie erhalten eine Benachrichtigung, sobald wir ein Ergebnis haben.',
      confirmChip: 'Ihr aktueller Anschluss bleibt bis zum Umzugsdatum aktiv.',
      confirmVariant: 'info',
    },
    accordion: {
      label: 'Was passiert als nächstes?',
      content: [
        { label: 'Status',           previous: null, current: 'Verfügbarkeit wird geprüft',  delta: null },
        { label: 'Umzugsdatum',      previous: null, current: '1. August 2026',               delta: null },
        { label: 'Auftragsnummer',   previous: null, current: '#UMZ-2026-00931',               delta: null },
        { label: 'Nächster Schritt', previous: null, current: 'Wir melden uns in 2–3 Tagen',  delta: null },
      ],
    },
    primaryCta: 'Auftragsstatus ansehen',
    feedbackBlock: false,
    secondaryCta: 'Hilfe anfordern',
  },
  {
    id: '13',
    title: 'Kündigung bestätigt — Magenta L',
    serviceChip: 'Magenta L · +49 222 222 2222',
    aiExplanation: {
      headline: 'Wir haben Ihre Kündigung bestätigt',
      body: 'Ihr Magenta L Vertrag endet am 31. Juli 2026. Bis dahin können Sie alle Leistungen wie gewohnt nutzen.',
      confirmChip: 'Ihre Rufnummer +49 222 222 2222 bleibt bis zum 31. Juli aktiv.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was passiert nach der Kündigung?',
      content: [
        { label: 'Vertragsende',          previous: null, current: '31. Juli 2026',    delta: null },
        { label: 'Letzte Abbuchung',      previous: null, current: '1. Juli 2026',     delta: null },
        { label: 'Nummer portierbar bis', previous: null, current: '31. Juli 2026',    delta: null },
        { label: 'SIM-Karte',             previous: null, current: 'Bitte vernichten', delta: null },
      ],
    },
    primaryCta: 'Kündigungsbestätigung als PDF',
    feedbackBlock: false,
    secondaryCta: 'Kündigung widerrufen',
  },
  {
    id: '14',
    title: 'Rechnung Internet — Mai 2026',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Ihre Rechnung ist um 5 € gesunken',
      body: 'Ihr Treuerabatt ist jetzt aktiv. Er wird automatisch jeden Monat abgezogen und gilt für die nächsten 12 Monate.',
      confirmChip: 'Dieser Rabatt bleibt bis Mai 2027 aktiv — kein Handlungsbedarf.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was hat sich geändert?',
      content: [
        { label: 'Fibre 1000 Grundpreis', previous: '39,99 €', current: '39,99 €', delta: 'Keine Änderung' },
        { label: 'Treuerabatt',           previous: '0,00 €',  current: '−5,00 €', delta: '−5,00 €' },
        { label: 'Gesamtbetrag',          previous: '39,99 €', current: '34,99 €', delta: '−5,00 €' },
      ],
    },
    primaryCta: 'Rechnung als PDF',
    feedbackBlock: true,
    secondaryCta: null,
  },
  {
    id: '15',
    title: 'Störung behoben — Internet',
    serviceChip: 'MagentaZuhause · Internet',
    aiExplanation: {
      headline: 'Ihr Internet läuft wieder normal',
      body: 'Wir haben die Störung in Ihrem Gebiet um 14:35 Uhr behoben. Alle Verbindungen sind wieder auf voller Geschwindigkeit.',
      confirmChip: 'Keine weiteren Aktionen nötig — alles ist wieder in Ordnung.',
      confirmVariant: 'success',
    },
    accordion: {
      label: 'Was war die Ursache?',
      content: [
        { label: 'Ursache',             previous: null, current: 'Technischer Defekt im Netzknoten', delta: null },
        { label: 'Betroffener Bereich', previous: null, current: 'Köln-Ehrenfeld',                   delta: null },
        { label: 'Beginn der Störung',  previous: null, current: '11:20 Uhr',                         delta: null },
        { label: 'Behoben um',          previous: null, current: '14:35 Uhr',                          delta: null },
      ],
    },
    primaryCta: null,
    feedbackBlock: false,
    secondaryCta: null,
  },
];
